plugins {
	id 'io.github.goooler.shadow' version '8.1.7' apply false
	id 'dev.architectury.loom' version '1.13-SNAPSHOT' apply false
	id 'io.github.goooler.shadow' version '8.1.7' apply false
}

apply plugin: 'architectury-plugin'

architectury {
	minecraft = project.minecraftVersion
}

allprojects {
	group = rootProject.group
	version = rootProject.modVersion
}

subprojects {
	apply plugin: 'dev.architectury.loom'
	apply plugin: 'architectury-plugin'

	base {
		archivesName = "$rootProject.name-$rootProject.minecraftVersion-$project.name"
	}

	repositories {
		maven {
			name = "CurseMaven"
			url = "https://www.cursemaven.com"
		}
		maven {
			name = "LadySnake"
			url = 'https://maven.ladysnake.org/releases'
		}
	}

	dependencies {
		minecraft "net.minecraft:minecraft:$rootProject.minecraftVersion"
		mappings loom.officialMojangMappings()

		modImplementation files("../libs/Iceberg-1.21.3-common-1.2.10.jar")
		modImplementation files("../libs/LegendaryTooltips-1.21.3-common-1.5.0.jar")
		modImplementation "curse.maven:adorned-1036809:5515068"
		modImplementation "curse.maven:accessories-938917:5576244"
		modImplementation "curse.maven:accessoriestrinkets-1005680:5575593"
		modImplementation("org.ladysnake.cardinal-components-api:cardinal-components-base:6.1.0")
		modImplementation("org.ladysnake.cardinal-components-api:cardinal-components-entity:6.1.0")
	}

	java {
		sourceCompatibility = JavaVersion.VERSION_21
		targetCompatibility = JavaVersion.VERSION_21
	}

	tasks.withType(JavaCompile).configureEach {
		it.options.release = 21
	}

	remapJar {
		destinationDirectory = file("$buildDir/../../output")
	}
}
